### ISSUE TITLE
Problem Statement-Shusheng

### ISSUE THREAD

**Issue by sccdsyad8663** [sccdsyad8663/Shusheng-CAS741#1]
Hi Professor Smith,

Please review the problem statement and the link is 
https://github.com/sccdsyad8663/Shusheng-CAS741/blob/master/ProblemStatement/ProblemStatement.pdf

@smiths

**Comment by smiths** [comment]
Hello @sccdsyad8663.  Your problem statement is approved.  I am basing my approval on the fact that you have done portions of the work already.  If that is not the case, we should revisit the issue of the scope of the project.

I have added some comments to your problem statement and pushed a new version to your repo.
