### ISSUE TITLE
Test plan:  Automated image comparison?

### ISSUE THREAD

**Issue by palmerst** [sccdsyad8663/Shusheng-CAS741#11]
A lot of your tests output images, which I assume will be compared against a reference image that is known to be correct. These tests are listed as automated: do you have a method for automatically judging image equality?

**Comment by sccdsyad8663** [comment]
In fact, the goal of my project is to calculate the volume of tumor. So if the computed volume is close to the groudtruth volume obtained from doctors, then the tests of output images can be passed.
