### ISSUE TITLE
Test plan:  Is code inspection a formal test?

### ISSUE THREAD

**Issue by palmerst** [sccdsyad8663/Shusheng-CAS741#12]
You write under non-testing based verification:  "Code inspection in Visual Studio performs. It can find defects and also spot any process improvement if any."  Is this more formal/rigourous than the standard set of syntax checking/highlighting tools offered by an IDE during development? If not I don't think that this really belongs as part of the test plan.

**Comment by sccdsyad8663** [comment]
Code Inspection is a kind of static testing, which belongs to Non-Testing Based Verification. So, I have used it in the process of wtring the code.
