### ISSUE TITLE
Test plan:  Possibly conflicting information

### ISSUE THREAD

**Issue by palmerst** [sccdsyad8663/Shusheng-CAS741#14]
In section 4.3 you write "Verification of correctness and output of intermediate steps (such as wall removal module, output of segmentation module, etc.) will be tested manually."  You have wall removal and segmentation system tests that are automated -- this seems like it conflicts with the statement that they will be tested manually.

**Comment by sccdsyad8663** [comment]
In the first draft, I want to verify the output of intermediate steps by comparing the segmentations from doctors and those by the proposed method. But the goal of my project is to obtaine the volume of tumor, so I modified the approach of how to perform the tests. Please see the [document](https://github.com/sccdsyad8663/Shusheng-CAS741/blob/master/Doc/TestPlan/TestPlan.pdf)
