### ISSUE TITLE
Test plan:  Static analysis tools

### ISSUE THREAD

**Issue by palmerst** [sccdsyad8663/Shusheng-CAS741#15]
You mention in section 4.4 that Visual Studio offers a suite of static analysis tools, and you list categories of concern that they can address.  This set of tools is not mentioned anywhere else in the document.  Are you actually going to perform testing using these tools?  I think you should describe how you will use these tools somewhere, or remove them from the Verification Tools section.

**Comment by sccdsyad8663** [comment]
OK. I have removed them from the Verification Tools section.
