### ISSUE TITLE
Module Guide Review - Decomposition Module - Input Module (M4)

### ISSUE THREAD

**Issue by slimpotatoes** [sccdsyad8663/Shusheng-CAS741#16]
Hi @sccdsyad8663 ,

Please find some comments I propose for your module review. :)

In M4, the services are stated as below:

> Converts the input data into the data structure used by the input parameters module.

I can't see any reference to a module "input parameters". I think you refer to module that was used in the template but is not present in your Module Guide.

**Comment by sccdsyad8663** [comment]
Sorry, I indeed refered to the module in the template and there is no imput parameters module. Now I have modified it ([here](https://github.com/sccdsyad8663/Shusheng-CAS741/blob/master/Doc/Design/MG/MG.pdf)).
