### ISSUE TITLE
Module Guide Review - Decomposition Module - Vessel Removal (M6)

### ISSUE THREAD

**Issue by slimpotatoes** [sccdsyad8663/Shusheng-CAS741#17]
The secrets of the Vessel Removal Module are stated as below:

> Services: Removes the wall and then get a “VesselFeatureImage” with vessel pixel “removed”.

I imagine the vessel removal should remove the vessel else you have two module (M5) and (M6) that looks to do the same thing.

**Comment by sccdsyad8663** [comment]
Sorry, it was a typo and it should be "Removes the vessel". I have modified it ([here](https://github.com/sccdsyad8663/Shusheng-CAS741/blob/master/Doc/Design/MG/MG.pdf)).
