### ISSUE TITLE
Module Guide Review - Hierarchy figure

### ISSUE THREAD

**Issue by slimpotatoes** [sccdsyad8663/Shusheng-CAS741#18]
Based on your definition of the Output Module (M11), I think that the output module should use the Hardware Hiding Module. So I suggest to draw an arrow from M11 to M1. 

Based on your definition of the Evaluation Module (M12), I don't see how the Evaluation Module is using the Hardware Hiding Module. The input/output modules are already present to import and display the results so the evaluation module could be calculation module only used by the control module. So I suggest to remove the arrow from M12 to M1.

**Comment by sccdsyad8663** [comment]
That is great. I have removed the arrow from M12 to M1 (https://github.com/sccdsyad8663/Shusheng-CAS741/blob/master/Doc/Design/MG/MG.pdf)
