### ISSUE TITLE
Module Guide Review - Traceability Matrix

### ISSUE THREAD

**Issue by slimpotatoes** [sccdsyad8663/Shusheng-CAS741#19]
In the Anticipated Change and Module table, there should be a one to one match between an anticipated change and a module. If AC5 occurs, only one module should be modified else it removes one interest of decompose the software in separated modules.

I think you can change AC5 to be more specific and match your module definition. I suggest to divide AC5 in 3 different anticipated changes as follows:
- AC5-a : implementation of the processing method to remove the wall
- AC5-b : implementation of the processing method to remove the vessel
- AC5-c: growth model of the tumor attached to the walls and the vessels causing the aggregated features images.

Then AC5-a is mapped with M5 only, AC5-b with M6 only and AC5-c with M7 only.

**Comment by sccdsyad8663** [comment]
Thanks for your advice. I have modified the table and reached one module one secret one anticipated change.

**Comment by sccdsyad8663** [comment]
Thanks for your advice. I have modified the table and reached one module one secret one anticipated change.
