### ISSUE TITLE
Please adjust your folder structure to match the blank template

### ISSUE THREAD

**Issue by smiths** [sccdsyad8663/Shusheng-CAS741#2]
You only have the folders from inside the Doc folder.  You should also have the src and other folders from the Blank Project Template.  Your folder structure should also follow the same folder hierarchy as in the original blank template.

**Comment by sccdsyad8663** [comment]
Thank you for your commentary. The folder structure have been modified according to your requirement.

**Comment by sccdsyad8663** [comment]
Thank you for your commentary. The folder structure have been modified according to your requirement. @smiths

**Comment by smiths** [comment]
Looks good.
