### ISSUE TITLE
MIS: State Variables

### ISSUE THREAD

**Issue by aschaap** [sccdsyad8663/Shusheng-CAS741#25]
In section 6 (MIS of Control Flow Module), a number of state variables are listed. These do not occur under 'transition', so it would seem they are not modified during the execution of the module. Is this correct? If so, they should probably not be state variables. If I remember correctly, a common state variable for a control flow module would be a file or the screen. I think the file is the relevant one here.

**Comment by sccdsyad8663** [comment]
You are right. They should be environment variables. I have modified them ([here](https://github.com/sccdsyad8663/Shusheng-CAS741/blob/master/Doc/Design/MIS/MIS.pdf)).
