### ISSUE TITLE
MIS: Notation

### ISSUE THREAD

**Issue by aschaap** [sccdsyad8663/Shusheng-CAS741#26]
I noticed a lot of types like "itk::ImageFileReader<float> InputReaderType". I think it would help the reader if you could define this notation in the Notation section, especially for those who are not familiar with the particular (programming?) language this is based on.

**Comment by sccdsyad8663** [comment]
Sorry, I designed the MIS according to the code I had written. According to the comments, MIS should be more abstract and I have modified it.
