### ISSUE TITLE
MIS: Output Module

### ISSUE THREAD

**Issue by aschaap** [sccdsyad8663/Shusheng-CAS741#27]
In section 14.3.1, I'm confused by the output 'V' for the 'cout' access program listed in the table. I assume this means volume, as per the Table of Units in the SRS. The transition function seems to be C++ code, where V is given to cout as an input rather than an output. I understand that this prints it to the standard output, but this is technically a side-effect instead of an output; essentially, another (hypothetical) function cannot really get V from this cout routine, and do things with it, as it is printed rather than returned. Perhaps it would be good to differentiate between these two results?

Furthermore, I see more access programs under 'Semantics' than 'Syntax'. If these are internal functions, they should be listed under a subheading named as such, otherwise the table under 'Syntax' could be updated to contain all these functions.

**Comment by sccdsyad8663** [comment]
I have added something to output module, which is more clear.

For more access programs  under 'Semantics' than 'Syntax', there may be something wrong with writing in the first draft.  I have modified it. Please see it again.
