### ISSUE TITLE
MIS: Appendix

### ISSUE THREAD

**Issue by aschaap** [sccdsyad8663/Shusheng-CAS741#28]
I found the information in the appendix quite useful. However, I think it makes more sense to a first-time reader if this information was close to the beginning of the document, since it introduces the notation I was confused by (as noted in issue #26). I also noticed a typo, I think by 'framwork' you mean 'framework'. I also noticed some missing articles (the/a/an). While I'm hesitant to include this, I think it may help: https://owl.english.purdue.edu/owl/resource/540/01/ . I found this page after some searching, and it explains their usage pretty well.

**Comment by sccdsyad8663** [comment]
I have modified the MIS to make it more abstract and I do not use the notation from my code, so I think it is ok to put it in appedix.  Thanks for your careful reading. I will read and learn the link you mentioned.
