### ISSUE TITLE
MIS: Evaluation Module section structure

### ISSUE THREAD

**Issue by aschaap** [sccdsyad8663/Shusheng-CAS741#29]
I noticed that the semantics of the module are described under the Uses heading. Maybe it's better to add a 'Semantics' heading above this information to separate it from the 'Uses' information? Ultimately, syntax would be good too, to be consistent with the rest of the document. (Following the template structure more closely for this module would help as well.)

**Comment by sccdsyad8663** [comment]
OK. I will try to follow the template structure.
