### ISSUE TITLE
SRS

### ISSUE THREAD

**Issue by sccdsyad8663** [sccdsyad8663/Shusheng-CAS741#3]
Dear professor Smith,

Please kindly review my SRS. It is not easy for me to write and finish SRS in such complicated Latex Framework, but I have tried my best to complete it. I will improve it as per your comments and requirements.  
Thank you! @smiths 

https://github.com/sccdsyad8663/Shusheng-CAS741/blob/master/Doc/SRS/SRS.pdf

Best regards,
Shusheng

**Comment by smiths** [comment]
Hello Shusheng.  I am sorry, but I do not have time to review your entire document.  I have had similar requests from others and I have had to say no.  It wouldn't be fair to others in the class.  I am happy to respond to issues, but they need to be specific questions.  The issues posted by Geneva are a good example:

https://github.com/GenevaS/CAS741/issues?q=is%3Aissue+is%3Aclosed
