### ISSUE TITLE
For system constrains, must this project rely on VolView?

### ISSUE THREAD

**Issue by MaXiaoye** [sccdsyad8663/Shusheng-CAS741#4]
Dear Shusheng,

In system constrains part, I see you mention the use of VolView. Does this mean the project must be implemented on VolView ? I wonder maybe the method and algorithm can be used in other platforms as well.

Thanks !
Xiaoye

**Comment by sccdsyad8663** [comment]
"VolView is an intuitive, interactive system for volume visualization that allows researchers to quickly explore and analyze complex 3D medical or scientific data." So, it can be used to open the CT images and helpful to analyze the tumor. It is just a software and the project is not implemented on it.
