### ISSUE TITLE
For general definition(GD) part.

### ISSUE THREAD

**Issue by MaXiaoye** [sccdsyad8663/Shusheng-CAS741#5]
Dear Shusheng,

Seems there is no GD in this project. May be you can update GD by explicitly saying no GD for this problem such as "there are no general definitions for the current problem"

Thanks
Xiaoye

**Comment by sccdsyad8663** [comment]
OK, thanks for your advice.

**Comment by smiths** [comment]
@sccdsyad8663 , your response to @MaXiaoye is ambiguous.  It is unclear whether you will follow his advice.  If you will, then you should edit the SRS and point to the specific commit that addresses the requested change.  If not, you should explain why not.  Either way, you should close the issue when you have completed dealing with it.

**Comment by sccdsyad8663** [comment]
I am sorry about my ambiguous response. I will give a clear response to MaXiaoye. Thanks for your comment. @smiths
