### ISSUE TITLE
Question about non-functional requirements.

### ISSUE THREAD

**Issue by MaXiaoye** [sccdsyad8663/Shusheng-CAS741#6]
Dear Shusheng,

Normally for non-functional requirements, we always talk about content like correctness or reusability for a project.
Why existing content is considered as non-functional requirements ? It seems like a data definition.

Thanks 
Xiaoye

**Comment by sccdsyad8663** [comment]
According to the comment in the SRS template document, it requires to provide a fit criterion to verifify the method, so relative error in my document is the evaluation of the method in which the volumes of ground truth are compared to those obtaind by the mothod.
