### ISSUE TITLE
Should the correctness of imput CT image included in data constrains ?

### ISSUE THREAD

**Issue by MaXiaoye** [sccdsyad8663/Shusheng-CAS741#7]
Dear Shusheng,

I see correctness of input CT is very important for this project.
So I wonder if this should belong to data constrains.
Or the current content refers to correctness of input CT ?

Thanks
Xiaoye

**Comment by sccdsyad8663** [comment]
Actually, the original CT images obtained from 320-slice CT machine is different across different organs. For lung tumor, the range is -1050HU to 2542HU. That is, the input CT is objectively provided from CT machine, but the usrs need to input the parameters to extract the tumor region
